name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm run test-with-emulators:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
